- name: Get ID for docker network
  ansible.builtin.command:
    cmd: docker network ls --filter name=docker-network --format "{{ '{{.ID}}' }}"
  register: docker_network_id

- name: Add IPTables rule for docker network at port 9100
  ansible.builtin.command:
    cmd: iptables -A INPUT -i {{ docker_network_id.stdout }} -p tcp --dport 9100 -j ACCEPT
  when: docker_network_id.stdout | length > 0 
  ignore_errors: yes 