- name: Create Vault directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "1000"
    group: "1000"
  with_items:
    - "/opt/vault"
    - "/opt/vault/config"

- name: Copy Vault config
  template:
    src: vault.hcl.j2
    dest: "/opt/vault/config/vault.hcl"
    mode: '0644'
    owner: "1000"
    group: "1000"