- hosts: server
  become: yes
  roles:
    - essentials
    - docker
    - utils
    - security

- hosts: server
  become: yes
  roles:
    - monitoring
    - vault        
    - docker-compose
    - { role: vault-init, when: init == 'true' }
    - backups
    - { role: restore, when: restore == 'true' }

- hosts: worker
  become: yes
  roles:
    - jenkins_worker
    - jenkins-utils
    - sonarqube