- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.12

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Ensure Python3 and required packages are installed
      apt:
        name: 
          - python3
          - python3-pip
          - python3-six 
        state: present

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes