---
- hosts: all
  become: yes
  roles:
    - essentials
    - docker
    - utils
    - security

- hosts: all
  become: yes
  roles:
    - monitoring
    - docker-compose
    - backups

- hosts: all
  become: yes
  tasks:
    - include_role:
        name: restore
      when: restore == 'true'