- hosts: all
  become: yes
  roles:
    - essentials
    - docker
    - utils
    - security

- hosts: all
  become: yes
  roles:
    - monitoring
    - vault        
    - docker-compose
    - { role: vault-init, when: init == 'true' }
    - backups
    - { role: restore, when: restore == 'true' }

    
# - hosts: all
#   become: yes
#   tasks:
#     - include_role:
#         name: restore
#       when: restore == 'true'
