- name: Create docker-compose directory
  file:
    path: /opt/docker-compose
    state: directory
    mode: '0755'

- name: Create Artifactory configuration directory
  file:
    path: /opt/artifactory/var/etc/artifactory
    state: directory
    mode: '0755'

- name: Create Artifactory system.yaml file
  template:
    src: system.yaml
    dest: /opt/artifactory/var/etc/artifactory/system.yaml
    mode: '0644'


- name: Copy docker-compose.yml file
  template:
    src: docker-compose.yml.j2
    dest: /opt/docker-compose/docker-compose.yml

- name: Run Docker Compose 
  command: docker-compose up -d
  args:
    chdir: /opt/docker-compose
  become: true


# - name: Create docker-compose directory
#   file:
#     path: /opt/docker-compose
#     state: directory
#     mode: '0755'

# - name: Copy docker-compose.yml file
#   template:
#     src: docker-compose.yml.j2
#     dest: /opt/docker-compose/docker-compose.yml

# - name: Run Docker Compose 
#   command: docker-compose up -d
#   args:
#     chdir: /opt/docker-compose
